### ISSUE TITLE
Hoarse sound when using realtime inference

### ISSUE THREAD

**Issue by Benjamin-Fairy** [CNChTu/Diffusion-SVC#20]
I trained one combo model, and **it works good under offline inference** in main.py, but using gui_realtime.py can only make a hoarse sound and cannot hear any pronunciation clearly(pitch seems to be correct). I've tried to change input devices\upgrade torch, but nothing works.

Following are setting snapshots.

Offline Inference
<img width="1240" alt="image" src="https://github.com/CNChTu/Diffusion-SVC/assets/38180912/31a3c1a7-5b55-4d60-ab6b-cb8efb633b1a">

Realtime Inference
![image](https://github.com/CNChTu/Diffusion-SVC/assets/38180912/b93b62f0-8b8e-445e-b8d6-a07620d4f643)

Have any ideas or workarounds?

**Comment by CNChTu** [comment]
That might be a bug in mask for hubert，set lower loudness threshold maybe can avoidance. I am trying to fix it.

**Comment by CNChTu** [comment]
Set lower loudness threshold maybe can avoidance. It is not a bug,  Perhaps due to the current method of calculating masks, I will add a switch to choose whether to use masks or not.

**Comment by Benjamin-Fairy** [comment]
Thanks for reply. I've tried to set loudness threshold to -60, but it also works improperly. Fortunatelly I could hear  a word or two correctly processed, that's much better. Hope to work it out.

**Comment by yxlllc** [comment]
Check if the gain of your microphone is too low or the recording is too noisy？

**Comment by CNChTu** [comment]
You can try update code， then take "use hubert mask"(使用hubert遮罩) off in gui.

**Comment by Benjamin-Fairy** [comment]
Fine, it works perfectly! Thanks for your strong support!
