### ISSUE TITLE
The sample rate of the input audio may cause problem

### ISSUE THREAD

**Issue by AliceNavigator** [CNChTu/Diffusion-SVC#21]
In my case, only use shallow model, the input audio sample rate is 22050Hz, but the training audio and config_shallow.yaml sample rate are both 44100Hz

its report "**RuntimeError: The size of tensor a (336) must match the size of tensor b (760) at non-singleton dimension 2**"

Then I convert sample rate to 44100Hz, it works fine

**Comment by CNChTu** [comment]
I fix it in https://github.com/CNChTu/Diffusion-SVC/commits/main

**Comment by CNChTu** [comment]
But I still recommend using the same sampling rate for shallow diffusion on the input source ,if you need do that
