### ISSUE TITLE
Voice got stuttered and lagged during realtime-inference

### ISSUE THREAD

**Issue by Benjamin-Fairy** [CNChTu/Diffusion-SVC#23]
During realtime inference, the output voice got stuttered and lagged sometimes. Changing input/output devices or combo models didn't work(Decreasing historical blocks  may mitigate the problem). Problem can be recurred when switching foreground programs or decreasing speedup. When the problem occurs, there is no explicit abnormal resource usage(cuda and video memory usage). By the way, the same problem can be met in DDSP-SVC project.

Following is demo video.

https://github.com/CNChTu/Diffusion-SVC/assets/38180912/811e0b6d-65a9-477e-bed4-0d42320a4667

Have any idea or workaround?

**Comment by CNChTu** [comment]
出现这种情况是推理耗时太久了，没有在下一轮之前合成出语音，就会重复播放缓冲区的内容。使用更好的硬件或提高加速倍数来减少推理时间即可。

**Comment by Benjamin-Fairy** [comment]
Fine,😭
