### ISSUE TITLE
How to use whisper-ppg as encoder?

### ISSUE THREAD

**Issue by futorio** [CNChTu/Diffusion-SVC#24]
Hello! In training Diffusion model table has "whisper-ppg(only can use with sovits)" row, but in config encoder has choices: "'hubertsoft', 'hubertbase', 'hubertbase768', 'contentvec', 'contentvec768' or 'contentvec768l12' or 'cnhubertsoftfish'". How can i use pretrain whisper model? Thank you!

**Comment by CNChTu** [comment]
You can use the pretrain whisper model in https://github.com/svc-develop-team/so-vits-svc
This repository is currently not supported.
