### ISSUE TITLE
音域问题

### ISSUE THREAD

**Issue by hpx502766238** [CNChTu/Diffusion-SVC#36]
介绍说naive存在音域问题。但我实际测试中，在没有训练naive情况下，仅训练浅扩散模型或完全扩散模型，两者练出的模型中低音正常，高音（F5以上）都比较虚弱，主要表现为音量低、附带电音（tensorboard中播放的效果），貌似是扩散模型的问题。数据集有90多分钟，数据集应该不算小吧。我尝试修改配置文件中f0的频率上限并重新预处理训练，但貌似不起作用。

**Comment by CNChTu** [comment]
如果是生成的频谱没有问题而声音异常，可能是声码器的音域不够了（G5）。可以试试使用fish-diff的声码器，有1200Hz的上限。
https://github.com/fishaudio/fish-diffusion

**Comment by hpx502766238** [comment]
> 
但是NSF-HiFiGAN官方写的输入频率是40-16000Hz，而且DDSP也用了相同的声码器进行增强，我尝试过用DDSP+NSF-HiFiGAN声码器增强后可以全覆盖6组的

**Comment by CNChTu** [comment]
DDSP使用此社区声码器增强是使用了波形上的特殊方法提高声码器的音域限制的。此社区声码器普遍认为上限就在G5附近。

**Comment by CNChTu** [comment]
更新更好的声码器或许会在未来到来，但是目前只有社区声码器权重和fish-diff的声码器权重可选。
