### ISSUE TITLE
FCPE fails to import

### ISSUE THREAD

**Issue by RainaObi** [CNChTu/Diffusion-SVC#37]
When trying to use FCPE as a f0 extractor the following error appears: `[Errno 2] No such file or directory: 'exp/f0bce_test_R004_cu0\\config.yamI'`
It's looking for a config.yaml file for the FCPE model, but this shouldn't be the case.

**Comment by RainaObi** [comment]
#38  was submitted to address this issue.

**Comment by CNChTu** [comment]
Thank you for your PR. I'll move the path to pretrain/fcpe after marge the PR.
