### ISSUE TITLE
欢迎使劲锤我

### ISSUE THREAD

**Issue by MaxMax2016** [CNChTu/Diffusion-SVC#49]
@NaruseMioShirakana 我2022年的项目，都能被你锤成碰瓷你2023年的diffusion_svc，给你使劲点赞。

**Comment by CNChTu** [comment]
![Uploading X32J3URARA]$W56CO2E$]%0.png…]()

**Comment by CNChTu** [comment]
见置顶：https://www.bilibili.com/read/cv27101514
本项目是diffusion svc，并非diff svc

**Comment by MaxMax2016** [comment]
![diffusion_svc](https://github.com/CNChTu/Diffusion-SVC/assets/16432329/9b0a2f7e-021e-43bc-93f4-8f717e9e99dc)
 
哟，敢做不敢认啦
