### ISSUE TITLE
关于推理哑音的一些疑问

### ISSUE THREAD

**Issue by mcoi-dev** [CNChTu/Diffusion-SVC#54]
问题：在底模上微调了大约10000多步(naive和diff都训练了，`k_max_step=200`)，tensorboard一切正常，但是推理以下两个音频时出现了大量哑音。（colab和本地都跑了十几次，都是一样的结果（暑假跑到期末...）

数据集：中音居多，400条左右，44.1KHz

python版本：py310

pytorch版本：2.1.0

f0：crepe和rmvpe都试过

编码器：content_vec

系统平台：windows环境本地MX450（很渣，轻喷），colab linux环境T4

音频：1、水龙吟（只保留人声推理）（后半部分全部哑音）

2、只因你太美（推理时只保留人声）（自我介绍后存在大量电音和抽搐）

请问：

1、为什么会出现这些哑音，哑音主要是`f0`还是编码器还是模型引起的？

2、如何解决这些哑音，如果解决不了请问
什么模型可以较好的解决这个问题

（刚入坑SVC，不是特别懂，请大佬不要喷）

输入歌声：https://pan.huang1111.cn/s/lN8ZiL

**Comment by NLPV2011** [comment]
I dont know that why the audio was be muted, but some unexpected sound was made by some sounds from musical instruments or background noise, or because the model has not yet been effeciently trained

我不知道为什么音频被静音，但一些意想不到的声音是由某些乐器或背景噪音发出的，或者是因为模型没有经过有效的训练

**Comment by CNChTu** [comment]
你好，最近我也在期末所以没有及时注意到这个issues并回复。
哑音，主要应该还是f0，可能是未消除干净的和声和混响的影响。可以尝试加大力度获取更干净的输入源。
模型是否有问题我听不到输出不能做出判断

**Comment by CNChTu** [comment]
> I dont know that why the audio was be muted, but some unexpected sound was made by some sounds from musical instruments or background noise, or because the model has not yet been effeciently trained
> 
> 我不知道为什么音频被静音，但一些意想不到的声音是由某些乐器或背景噪音发出的，或者是因为模型没有经过有效的训练

SVC模型以及声码器都很依赖与外部输入的f0，如果输入的音频中的混响导致f0提取错误，那么模型就不能正常发音。

The SVC model and vocoder both rely heavily on external input f0. If factors such as reverberation in the input audio lead to errors in f0 extraction, the model will not be able to pronounce correctly.

**Comment by mcoi-dev** [comment]
> > I dont know that why the audio was be muted, but some unexpected sound was made by some sounds from musical instruments or background noise, or because the model has not yet been effeciently trained
> > 我不知道为什么音频被静音，但一些意想不到的声音是由某些乐器或背景噪音发出的，或者是因为模型没有经过有效的训练
> 
> SVC模型以及声码器都很依赖与外部输入的f0，如果输入的音频中的混响导致f0提取错误，那么模型就不能正常发音。
> 
> The SVC model and vocoder both rely heavily on external input f0. If factors such as reverberation in the input audio lead to errors in f0 extraction, the model will not be able to pronounce correctly.

感谢大佬的回复，我用AU去除混响后好了很多。
