### ISSUE TITLE
也许可以增加其他训练方式

### ISSUE THREAD

**Issue by AlphaOC101** [CNChTu/Diffusion-SVC#59]

**Comment by CNChTu** [comment]
请问具体是指什么？

**Comment by AlphaOC101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
                
            
        
    




    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by AlphaOC101** [comment]
比如训练onnx的模型什么的

**Comment by CNChTu** [comment]
onnx导出现在是支持的

**Comment by AlphaOC101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
                
            
        
    




    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by AlphaOC101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
                
            
        
    




    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
