### ISSUE TITLE
想问一下项目的方法论来源

### ISSUE THREAD

**Issue by thisisjacky6** [CNChTu/Diffusion-SVC#60]
请问此项目是基于论文DIFFSVC: A DIFFUSION PROBABILISTIC MODEL FOR SINGING VOICE CONVERSION，https://arxiv.org/abs/2105.13871 实现的吗？

**Comment by CNChTu** [comment]
不是的，和本项目关系更大的是
https://github.com/yxlllc/DDSP-SVC
和https://github.com/prophesier/diff-SVC

**Comment by thisisjacky6** [comment]
> 不是的，和本项目关系更大的是 https://github.com/yxlllc/DDSP-SVC 和https://github.com/prophesier/diff-SVC

谢谢
