### ISSUE TITLE
关于 v2.0 的一些疑问

### ISSUE THREAD

**Issue by TheFunny** [CNChTu/Diffusion-SVC#61]
有一些关于最新 2.0 版本的一些疑问想请教一下大佬：
1. 当前 v2.0 分支还会不会有大的改动？是否已经可以基于当前分支进行模型训练和推理？
2. v2.0 与 v1 的模型是否兼容呢？
3. v2.0 相比 v1 有哪些进步呢？
4. 如果要使用新的 hifi-vaegan 作为 vocoder，在训练模型时是否必须使用 hifi-vaegan，而不能使用 nsf-hifigan？
5. hifi-vaegan 相比 nsf-hifigan 有哪些优点或缺点呢？
6. 如果新旧模型不兼容，当前是否已计划训练发布新的底模呢？
7. 如果要使用 v2.0 进行底模训练，配置文件需要针对性做一些修改吗（以及有无推荐的 batch size 和 lr 参数）？

如果有不方便回答的问题还请略过就好。

**Comment by CNChTu** [comment]
感谢你的喜爱！
1.1、2.0分支扩散部分基本确定，但是主网络可能是多个选择并行，直到确定最优解。前级(也即naive和naive v2)模型还会持续改动，正在添加基于GAN和基于glow的模型，兼顾速度和质量。
1.2、训练和推理是可以的，我会尽力保证兼容性。另外目前readme还没写。
2、2.0代码尽可能会兼容1.0的模型。2.0的目的是解耦所有模块，并尽可能添加特性，以寻得最优解，所以2.0会有很多并行的选择。找到最优解后我会尽快重构到下一版本，将不那么好的选择去除。
3、代码更易拓展，支持更多的选择和更好的模型分发方式。
4、训练模型显然声码器可以不参与，但是预处理和训练时的验证都需要用到，所以最好带上声码器。
5、hifivaegan优点是显著巨大的音域；缺点是扩散模型的学习hifi vaegan中间特征的难度会比mel高得多。
6、2.0会在正式发布时给出底模，这将在生成模型的前级实验完成后进行。
7、具体请自行实验，问就是我也不知道.... 更重要的是，2.0支持很多种网络，甚至可以配置成1.0同款网络，所以其实不止训练参数需要调参，模型结构和参数也得调参，这里需要大量的实验，和上面说的前级改进一道成为2.0难产的最主要两个原因。

**Comment by TheFunny** [comment]
感谢解答！还有一个疑问，不知道是否有测试过音色泄露的情况？如果有的话，具体在多少量级下会明显产生呢？

**Comment by CNChTu** [comment]
没有测试过，这主要取决于编码器的性能，关于cvec如何解缠说话人请关注他们的论文和代码：
https://github.com/auspicious3000/contentvec

**Comment by TheFunny** [comment]
了解了，感谢！
